version: "3.6"
services:
  certbot:
    env_file: _deployment/certbot/.env
    image: certbot/dns-route53
    volumes:
      - certbot:/etc/letsencrypt
      - certbot:/var/lib/letsencrypt
    ports:
      - 4000:443
    entrypoint: certbot certonly --non-interactive --keep
                  --dns-route53 --dns-route53-propagation-seconds 30
                  -d www.prati.ba --agree-tos --email almir@optimum.ba
  postgres:
    # Postgres with automated backups to S3
    # https://github.com/tonda100/postgres-s3
    build:
      context: _deployment/postgres
    env_file: _deployment/postgres/.env
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
  prati_ba:
    build:
      context: .
      dockerfile: _deployment/prati_ba/Dockerfile
    env_file: _deployment/prati_ba/.env
    ports:
      - 4000:4000
      - 4001:4001
    restart: unless-stopped
    volumes:
      - certbot:/etc/letsencrypt
volumes:
  certbot:
    driver: local
  postgres:
    driver: local
