apiVersion: batch/v1
kind: Job
metadata:
  generateName: pratiba-migrations-
  labels:
    env: staging
  namespace: staging
spec:
  template:
    metadata:
      labels:
        env: staging
    spec:
      containers:
        - image: 833583610700.dkr.ecr.eu-central-1.amazonaws.com/pratiba
          name: pratiba-migrations
          command: ["sh", "-c", "bin/prati_ba eval 'PratiBa.Release.migrate' && bin/prati_ba eval 'PratiBa.Release.seed'"]
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-password
                  key: value
            - name: AWS_S3_ID
              valueFrom:
                secretKeyRef:
                  name: aws-s3-id
                  key: value
            - name: AWS_S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-s3-secret
                  key: value
            - name: ASSET_HOST
              value: static-staging-2345.prati.ba
            - name: AWS_S3_BUCKET
              value: staging-static.prati.ba
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: value
            - name: HOST
              value: staging-2345.prati.ba
            - name: MAXMIND_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: maxmind-license-key
                  key: value
            - name: POOL_SIZE
              value: "10"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secret-key-base
                  key: value
      imagePullSecrets:
        - name: aws-ecr-credentials
      restartPolicy: Never
