apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: pratiba-backendconfig-staging
spec:
  # Set timeout for websockets to one day
  timeoutSec: 86400
  # Wait a minute before pod starts getting terminated
  connectionDraining:
    drainingTimeoutSec: 60
