- op: add
  path: /metadata/annotations
  value:
    kubernetes.io/ingress.global-static-ip-name: pratiba-production
    networking.gke.io/managed-certificates: pratiba-production
- op: replace
  path: /spec/rules/0/host
  value: prati.ba
