apiVersion: batch/v1
kind: Job
metadata:
  name: pratiba-migrations
spec:
  template:
    spec:
      containers:
        - name: pratiba-migrations
          env:
            - name: ASSET_HOST
              value: static.prati.ba
            - name: AWS_S3_BUCKET
              value: static.prati.ba
            - name: HOST
              value: prati.ba
